"""Versioned catalog entries backed by existing Phase 4 snapshot RPCs."""

from __future__ import annotations

from typing import Any


def _snapshot_metric(
    metric_id: str,
    label: str,
    domain: str,
    description: str,
    unit: str,
    value_path: tuple[str, ...],
    dimensions: tuple[str, ...],
    aliases: tuple[str, ...],
    executor: str,
    *,
    dimension_paths: dict[str, tuple[str, ...]] | None = None,
) -> dict[str, Any]:
    return {
        "id": metric_id,
        "label": label,
        "domain": domain,
        "description": description,
        "unit": unit,
        "entity": "snapshot",
        "grain": "current snapshot",
        "competence": "estado atual da fonte; sem janela temporal",
        "deduplication": "deduplicação definida pela RPC instalada",
        "executor": executor,
        "value_path": value_path,
        "dimensions": dimensions,
        "filters": (),
        "aliases": aliases,
        "formula": description,
        "status": "snapshot",
        "exclusions": "não comparar com outro período sem uma fonte histórica dedicada",
        "dimension_paths": dimension_paths,
        "period_required": False,
    }


SNAPSHOT_METRIC_SPECS: dict[str, dict[str, Any]] = {
    "produtos.total_maquinas": _snapshot_metric(
        "produtos.total_maquinas",
        "Máquinas instaladas",
        "produtos",
        "Soma da quantidade de máquinas no parque instalado do snapshot atual.",
        "count",
        ("kpis", "totalMaquinas"),
        ("grupo", "marca", "modelo"),
        ("máquinas instaladas", "maquinas instaladas", "total de máquinas", "parque instalado", "parque"),
        "products_snapshot",
        dimension_paths={
            "grupo": ("porGrupo",),
            "marca": ("porMarca",),
            "modelo": ("topModelos",),
        },
    ),
    "produtos.clientes_com_parque": _snapshot_metric(
        "produtos.clientes_com_parque",
        "Clientes com parque",
        "produtos",
        "Quantidade de clientes distintos com máquinas no parque instalado.",
        "count",
        ("kpis", "clientesComParque"),
        (),
        ("clientes com parque", "clientes do parque"),
        "products_snapshot",
    ),
    "produtos.grupos_distintos": _snapshot_metric(
        "produtos.grupos_distintos",
        "Grupos de produto",
        "produtos",
        "Quantidade de grupos distintos no parque instalado.",
        "count",
        ("kpis", "gruposDistintos"),
        (),
        ("grupos de produto", "grupos distintos do parque"),
        "products_snapshot",
    ),
    "produtos.marcas_distintas": _snapshot_metric(
        "produtos.marcas_distintas",
        "Marcas instaladas",
        "produtos",
        "Quantidade de marcas distintas no parque instalado.",
        "count",
        ("kpis", "marcasDistintas"),
        (),
        ("marcas instaladas", "marcas do parque", "marcas distintas"),
        "products_snapshot",
    ),
    "admin.total_clientes": _snapshot_metric(
        "admin.total_clientes",
        "Clientes da carteira",
        "admin",
        "Quantidade de clientes distintos na carteira do snapshot atual.",
        "count",
        ("kpis", "totalClientes"),
        ("tipo_cliente", "uf", "consultor"),
        ("total de clientes", "clientes da carteira", "base de clientes", "carteira de clientes"),
        "admin_snapshot",
        dimension_paths={
            "tipo_cliente": ("porTipoCliente",),
            "uf": ("porUF",),
            "consultor": ("porConsultor",),
        },
    ),
    "admin.prospects": _snapshot_metric(
        "admin.prospects",
        "Prospects",
        "admin",
        "Quantidade de prospects na carteira do snapshot atual.",
        "count",
        ("kpis", "prospects"),
        (),
        ("prospects", "prospectes"),
        "admin_snapshot",
    ),
    "admin.ativos": _snapshot_metric(
        "admin.ativos",
        "Clientes ativos",
        "admin",
        "Quantidade de clientes ativos na carteira do snapshot atual.",
        "count",
        ("kpis", "ativos"),
        (),
        ("clientes ativos", "ativos da carteira"),
        "admin_snapshot",
    ),
    "admin.ufs_cobertas": _snapshot_metric(
        "admin.ufs_cobertas",
        "UFs cobertas",
        "admin",
        "Quantidade de UFs distintas na carteira do snapshot atual.",
        "count",
        ("kpis", "ufsCobertas"),
        (),
        ("ufs cobertas", "estados cobertos"),
        "admin_snapshot",
    ),
    "admin.consultores_carteira": _snapshot_metric(
        "admin.consultores_carteira",
        "Consultores da carteira",
        "admin",
        "Quantidade de consultores com clientes na carteira do snapshot atual.",
        "count",
        ("kpis", "consultoresCarteira"),
        (),
        ("consultores da carteira", "consultores com clientes"),
        "admin_snapshot",
    ),
    "operacional.tecnicos_ativos": _snapshot_metric(
        "operacional.tecnicos_ativos",
        "Técnicos ativos",
        "operacional",
        "Quantidade de técnicos presentes no agregado operacional atual.",
        "count",
        ("kpis", "tecnicosAtivos"),
        (),
        ("técnicos ativos", "tecnicos ativos"),
        "operational_snapshot",
    ),
    "operacional.km_total": _snapshot_metric(
        "operacional.km_total",
        "Quilometragem total",
        "operacional",
        "Soma da quilometragem registrada no agregado operacional atual.",
        "km",
        ("kpis", "kmTotal"),
        ("tecnico",),
        ("km total", "quilometragem total", "km rodados"),
        "operational_snapshot",
        dimension_paths={"tecnico": ("kmPorTecnico",)},
    ),
    "operacional.utilizacao_media": _snapshot_metric(
        "operacional.utilizacao_media",
        "Utilização média",
        "operacional",
        "Percentual médio de utilização dos técnicos no agregado operacional atual.",
        "%",
        ("kpis", "utilizacaoMedia"),
        (),
        ("utilização média", "utilizacao media"),
        "operational_snapshot",
    ),
    "operacional.percentual_ocioso": _snapshot_metric(
        "operacional.percentual_ocioso",
        "Percentual ocioso",
        "operacional",
        "Percentual de tempo ocioso no agregado operacional atual.",
        "%",
        ("kpis", "percentOcioso"),
        (),
        ("percentual ocioso", "tempo ocioso", "ociosidade"),
        "operational_snapshot",
    ),
    "operacional.eventos_agenda": _snapshot_metric(
        "operacional.eventos_agenda",
        "Eventos de agenda",
        "operacional",
        "Quantidade de eventos na agenda de serviços do snapshot atual.",
        "count",
        ("kpis", "eventosAgenda"),
        ("status", "tipo"),
        ("eventos de agenda", "eventos agenda", "agenda de serviços"),
        "operational_snapshot",
        dimension_paths={"status": ("agendaPorStatus",), "tipo": ("agendaPorTipo",)},
    ),
    "operacional.taxa_conclusao_agenda": _snapshot_metric(
        "operacional.taxa_conclusao_agenda",
        "Taxa de conclusão da agenda",
        "operacional",
        "Percentual de eventos concluídos sobre o total de eventos da agenda atual.",
        "%",
        ("kpis", "taxaConclusaoAgenda"),
        (),
        ("taxa de conclusão da agenda", "conclusão da agenda", "conclusao da agenda"),
        "operational_snapshot",
    ),
}
