// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
// A password login used to retry four 4s client-aborted requests. When the
// gateway was congested, the button remained in "Entrando..." for ~17s and
// could send multiple concurrent credential requests. One request with a
// realistic deadline gives a definitive result without this retry cascade.
const AUTH_LOGIN_ATTEMPTS = 1;
const AUTH_LOGIN_ATTEMPT_TIMEOUT_MS = 15_000;
const AUTH_LOGIN_RETRY_DELAY_MS = 0;

// Analytical RPCs can legitimately take longer than a regular REST request.
// Retrying an aborted request here used to multiply the same expensive query
// against PostgREST while the first execution was still being cancelled. Let
// the gateway return its own definitive response instead; retries for these
// requests are owned by the individual query only when they are safe.
const GENERAL_ATTEMPTS = 1;
const GENERAL_TIMEOUT_MS = 35_000;
const GENERAL_RETRY_DELAY_MS = 0;

export const AUTH_STORAGE_KEY = `sb-${new URL(SUPABASE_URL).hostname.split('.')[0]}-auth-token`;

function isPasswordLoginRequest(input: RequestInfo | URL, init?: RequestInit): boolean {
  const url = typeof input === 'string'
    ? input
    : input instanceof URL
      ? input.href
      : input.url;
  const method = (init?.method ?? (typeof Request !== 'undefined' && input instanceof Request ? input.method : 'GET')).toUpperCase();

  return method === 'POST'
    && new URL(url, window.location.origin).pathname.endsWith('/auth/v1/token')
    && new URL(url, window.location.origin).searchParams.get('grant_type') === 'password';
}

function waitForRetry(delayMs: number): Promise<void> {
  return new Promise((resolve) => window.setTimeout(resolve, delayMs));
}

/**
 * Some client networks intermittently stall while opening an HTTPS connection
 * before the request reaches Traefik. Retrying with a fresh, aborted fetch
 * keeps transient connection failures from crashing user actions or leaving
 * the login screen stuck.
 */
async function resilientSupabaseFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const isAuth = isPasswordLoginRequest(input, init);
  const maxAttempts = isAuth ? AUTH_LOGIN_ATTEMPTS : GENERAL_ATTEMPTS;
  const timeoutMs = isAuth ? AUTH_LOGIN_ATTEMPT_TIMEOUT_MS : GENERAL_TIMEOUT_MS;
  const retryDelay = isAuth ? AUTH_LOGIN_RETRY_DELAY_MS : GENERAL_RETRY_DELAY_MS;

  let lastError: unknown;

  for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
    const controller = new AbortController();
    const timeoutId = window.setTimeout(() => controller.abort(), timeoutMs);
    const parentSignal = init?.signal;
    const abortFromParent = () => controller.abort(parentSignal?.reason);

    if (parentSignal?.aborted) abortFromParent();
    else parentSignal?.addEventListener('abort', abortFromParent, { once: true });

    try {
      return await globalThis.fetch(input, { ...init, signal: controller.signal });
    } catch (error) {
      lastError = error;
      if (parentSignal?.aborted || attempt === maxAttempts) throw error;
      await waitForRetry(retryDelay);
    } finally {
      window.clearTimeout(timeoutId);
      parentSignal?.removeEventListener('abort', abortFromParent);
    }
  }

  throw lastError;
}

export function clearPersistedAuthSession(): void {
  try {
    localStorage.removeItem(AUTH_STORAGE_KEY);
    localStorage.removeItem(`${AUTH_STORAGE_KEY}-code-verifier`);
    localStorage.removeItem(`${AUTH_STORAGE_KEY}-user`);
  } catch (error) {
    console.warn('[Supabase] Failed to clear persisted auth session:', error);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: resilientSupabaseFetch,
  },
  auth: {
    storage: localStorage,
    storageKey: AUTH_STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
  }
});
