// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { resolveSupabaseUrl } from './url';

const CONFIGURED_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_URL = resolveSupabaseUrl({
  configuredUrl: CONFIGURED_SUPABASE_URL,
  isProduction: import.meta.env.PROD,
  origin: window.location.origin,
});
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
// Auth refresh/login is the dependency of every protected query. Give the
// token endpoint one bounded recovery attempt, without creating a retry storm.
const AUTH_TOKEN_ATTEMPTS = 2;
const AUTH_TOKEN_ATTEMPT_TIMEOUT_MS = 5_500;
const AUTH_TOKEN_RETRY_DELAY_MS = 400;

// Analytical RPCs can legitimately take longer than a regular REST request.
// Retrying an aborted request here used to multiply the same expensive query
// against PostgREST while the first execution was still being cancelled. Let
// the gateway return its own definitive response instead; retries for these
// requests are owned by the individual query only when they are safe.
const GENERAL_ATTEMPTS = 1;
const GENERAL_TIMEOUT_MS = 35_000;
const GENERAL_RETRY_DELAY_MS = 0;

// Keep the project key stable while the production transport moves behind the
// BI origin. Existing sessions are stored under the Supabase hostname key.
export const AUTH_STORAGE_KEY = `sb-${new URL(CONFIGURED_SUPABASE_URL).hostname.split('.')[0]}-auth-token`;

function isAuthTokenRequest(input: RequestInfo | URL, init?: RequestInit): boolean {
  const url = typeof input === 'string'
    ? input
    : input instanceof URL
      ? input.href
      : input.url;
  const method = (init?.method ?? (typeof Request !== 'undefined' && input instanceof Request ? input.method : 'GET')).toUpperCase();

  const parsed = new URL(url, window.location.origin);
  const grantType = parsed.searchParams.get('grant_type');
  return method === 'POST'
    && parsed.pathname.endsWith('/auth/v1/token')
    && (grantType === 'password' || grantType === 'refresh_token');
}

function waitForRetry(delayMs: number): Promise<void> {
  return new Promise((resolve) => window.setTimeout(resolve, delayMs));
}

/**
 * Some client networks intermittently stall while opening an HTTPS connection
 * before the request reaches Traefik. Retrying with a fresh, aborted fetch
 * keeps transient connection failures from crashing user actions or leaving
 * the login screen stuck.
 */
async function resilientSupabaseFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const isAuth = isAuthTokenRequest(input, init);
  const maxAttempts = isAuth ? AUTH_TOKEN_ATTEMPTS : GENERAL_ATTEMPTS;
  const timeoutMs = isAuth ? AUTH_TOKEN_ATTEMPT_TIMEOUT_MS : GENERAL_TIMEOUT_MS;
  const retryDelay = isAuth ? AUTH_TOKEN_RETRY_DELAY_MS : GENERAL_RETRY_DELAY_MS;

  let lastError: unknown;

  for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
    const controller = new AbortController();
    const timeoutId = window.setTimeout(() => controller.abort(), timeoutMs);
    const parentSignal = init?.signal;
    const abortFromParent = () => controller.abort(parentSignal?.reason);

    if (parentSignal?.aborted) abortFromParent();
    else parentSignal?.addEventListener('abort', abortFromParent, { once: true });

    try {
      const response = await globalThis.fetch(input, { ...init, signal: controller.signal });
      if (isAuth && [408, 425, 429, 500, 502, 503, 504].includes(response.status) && attempt < maxAttempts) {
        await waitForRetry(retryDelay);
        continue;
      }
      return response;
    } catch (error) {
      lastError = error;
      if (parentSignal?.aborted || attempt === maxAttempts) throw error;
      await waitForRetry(retryDelay);
    } finally {
      window.clearTimeout(timeoutId);
      parentSignal?.removeEventListener('abort', abortFromParent);
    }
  }

  throw lastError;
}

export function clearPersistedAuthSession(): void {
  try {
    localStorage.removeItem(AUTH_STORAGE_KEY);
    localStorage.removeItem(`${AUTH_STORAGE_KEY}-code-verifier`);
    localStorage.removeItem(`${AUTH_STORAGE_KEY}-user`);
  } catch (error) {
    console.warn('[Supabase] Failed to clear persisted auth session:', error);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: resilientSupabaseFetch,
  },
  auth: {
    storage: localStorage,
    storageKey: AUTH_STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
  }
});
